---
- hosts: django
  pre_tasks:
    - name: checkout site repo
      git:
        repo: https://github.com/cwgem/cwprogram.com
        dest: "{{ansible_env.HOME}}/cwprogram.com"
  roles:
    - role: iptables-common
    - role: portage-common
    - role: python35
    - role: django-appserver
    - role: nginx
  post_tasks:
    - name: load iptables
      command: /sbin/load-iptables.sh
      become: true
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      become: true
