---
- name: copy make.conf
  template: src=make.conf.j2 dest=/etc/portage/make.conf
  become: true

- name: ensure /etc/portage/profile
  file: path=/etc/portage/profile state=directory
  become: true

- name: ensure /etc/portage/repos.conf
  file: path=/etc/portage/repos.conf state=directory
  become: true

- name: ensure make.defaults
  file: path=/etc/portage/profile/make.defaults state=touch
  become: true

- name: test to see if it has been one week since last emerge --sync
  shell: test $(date "+%s") -gt $(date -d "$(</usr/portage/metadata/timestamp) +1 week" "+%s"
  register: timestamp_check
  changed_when: "timestamp_check.rc == 0"
  failed_when: "timestamp_check.rc > 1"
  notify:
  - sync and update

- name: add portage related iptables rules
  copy: src=portage_iptables.sh.j2 dest=/etc/iptables.d/portage_iptables.sh mode=0700
  become: true

- name: install basic packages
  portage: package={{item}} state=present
  with_items:
    - dev-vcs/git
    - dev-util/strace
    - app-misc/tmux
  become: true
